### PR TITLE
Enhancement/footer start

### PR DESCRIPTION
**Pull request by wumpfroot**
#25 Pull request to footer branch

### CODE REVIEW

**Comment by mz106** [comment]
Markus, could you please push wireframes/designs to to documentation branch before merging this code.

**Comment by wumpfroot** [comment]
> Markus, could you please push wireframes/designs to to documentation branch before merging this code.

Hi. No initial designs on this one and the navbar Im pushing soon.

**Comment by mz106** [comment]
The project needs some wireframes to keep consistant if other people work on a branch. Can you please push some wireframes prior to and more code pushes.

**Comment by mz106** [comment]
Could you also please add some screenshots for review.

**Comment by wumpfroot** [comment]
Footer_mobile
Footer_desktop

**Review by mz106 — CHANGES_REQUESTED** [review]
Please change menu items to page1, page2 etc.

**Comment by wumpfroot** [comment]
Footer_desktop_menu_items

**Review by mz106 — APPROVED** [review]
Approved

**Pull request merged**
