### PR TITLE
Enhancement header navbar mobile dropdown

### PR DESCRIPTION
**Pull request by wumpfroot**
Navbar layout ready for now

### CODE REVIEW

**Comment by wumpfroot** [comment]
Navbar_mobile_dropdownv2
Navbar_mobile v2jpg
Navbar_mobile_dropdown_landscape

**Comment by wumpfroot** [comment]
@mz106 Basic navbar is ready with a dropdown menu. From there, few changes can be made and pull it to main.

**Review by mz106 — APPROVED** [review]
Approved

**Comment by mz106** [comment]
@wumpfroot Okie dokie, approved

**Pull request merged**
