### PR TITLE
#12 Navbar mobile wireframe added to new branch

### PR DESCRIPTION
**Pull request by wumpfroot**

### CODE REVIEW

**Comment by mz106** [comment]
Markus, could you please put add some screenshots.

**Comment by wumpfroot** [comment]
Navbar_mobile_drawio

**Comment by mz106** [comment]
Thanks Markus. Could you please coordinate with Deviydas on this design/implementation as he has pushed some code for the header.

**Review by mz106 — APPROVED** [review]
Approved

**Pull request merged**
